module.exports = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SCHEDULE_INTERNAL_ERROR: 'SCHEDULE_INTERNAL_ERROR',
  BADGE_BE_USING: 'BADGE_BE_USING',
  BADGE_UN_USING: 'BADGE_UN_USING',
  BADGE_ID_NO_ENABLED: 'BADGE_ID_NO_ENABLED',
  INVALID_USER_COMPANY_AND_MOBILE: 'INVALID_USER_COMPANY_AND_MOBILE',
  NOT_FOUND_INDOOR_ID: 'NOT_FOUND_INDOOR_ID',
  RACKID_EXIST: 'RACKID_EXIST',
  PRIVATE_IP_HAS_BEEN_EXIST: 'PRIVATE_IP_HAS_BEEN_EXIST',
  RACKID_DOES_NOT_EXIST: 'RACKID_DOES_NOT_EXIST',
  UUID_DOES_NOT_EXIST: 'UUID_DOES_NOT_EXIST',
  ARGUMENTS_ERROR: (params) => { // params is a string
    if (params) return `ARGUMENT_ERROR: ${params}`;
    return 'ARGUMENT_ERROR';
  },
  STREAM_REST_CLIENT_ERROR: 'STREAM_REST_CLIENT_ERROR'
};
